import { type DeviceNodeData, type DevicePort } from '../diagram/model/interfaces';
import {
  ARDUINO_NANO_FOOTPRINT,
  BUZZER_ACTIVE_12MM_FOOTPRINT,
  CAP_100N_FOOTPRINT,
  CAP_470U_16V_FOOTPRINT,
  CAP_470U_25V_FOOTPRINT,
  cloneFootprint,
  GY_521_MPU6050_FOOTPRINT,
  RESISTOR_1K8_FOOTPRINT,
  RESISTOR_1K_FOOTPRINT,
  TB6612FNG_FOOTPRINT,
  type Footprint,
} from '../diagram/model/footprint';

export interface LibraryDevice {
  libraryId: string;
  template: DeviceNodeData;
}

const port = (
  id: string,
  label: string,
  direction: DevicePort['direction'],
  connectorType: string,
  wirevizDesignator?: string,
): DevicePort => ({
  id,
  label,
  direction,
  connectorType,
  ...(wirevizDesignator ? { wirevizDesignator } : {}),
});

const physicalDefinition = (footprint: Footprint) => ({
  footprintId: footprint.id,
  footprint: cloneFootprint(footprint),
  footprintRotation: 0 as const,
  footprintPitch: 20,
});

export const createBlankTemplate = (): DeviceNodeData => ({
  type: 'device',
  deviceId: '',
  manufacturer: '',
  model: '',
  category: '',
  location: '',
  ports: [],
});

/**
 * Catalogo funcional do Talus-Droid. Os labels preservam os designadores
 * eletricos usados no firmware, no header fisico ou na serigrafia do modulo.
 */
export const SEED_LIBRARY: LibraryDevice[] = [
  {
    libraryId: 'lib-arduino-nano',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Arduino',
      model: 'Nano',
      category: 'microcontroller',
      location: '',
      ...physicalDefinition(ARDUINO_NANO_FOOTPRINT),
      ports: [
        port('d13', 'D13', 'output', 'GPIO'),
        port('3v3', '3V3', 'input', 'Power'),
        port('aref', 'REF', 'input', 'GPIO'),
        port('a0', 'A0', 'input', 'GPIO'),
        port('a1', 'A1', 'input', 'GPIO'),
        port('a2', 'A2', 'input', 'GPIO'),
        port('a3', 'A3', 'input', 'GPIO'),
        port('a4', 'A4 / SDA', 'output', 'I2C', 'A4'),
        port('a5', 'A5 / SCL', 'output', 'I2C', 'A5'),
        port('a6', 'A6', 'input', 'GPIO'),
        port('a7', 'A7', 'input', 'GPIO'),
        port('5v', '5V', 'input', 'Power'),
        port('rst', 'RST', 'input', 'GPIO'),
        port('gnd', 'GND', 'input', 'Power'),
        port('vin', 'VIN', 'input', 'Power'),
        port('d12', 'D12', 'output', 'GPIO'),
        port('d11', 'D11 / BUZZER', 'output', 'PWM', 'D11'),
        port('d10', 'D10 / BIN2', 'output', 'GPIO', 'D10'),
        port('d9', 'D9 / BIN1', 'output', 'GPIO', 'D9'),
        port('d8', 'D8 / AIN2', 'output', 'GPIO', 'D8'),
        port('d7', 'D7 / AIN1', 'output', 'GPIO', 'D7'),
        port('d6', 'D6 / PWMB', 'output', 'PWM', 'D6'),
        port('d5', 'D5 / PWMA', 'output', 'PWM', 'D5'),
        port('d4', 'D4 / STBY', 'output', 'GPIO', 'D4'),
        port('d3', 'D3 / HALL_R', 'input', 'GPIO', 'D3'),
        port('d2', 'D2 / HALL_L', 'input', 'GPIO', 'D2'),
        port('gnd-2', 'GND 2', 'input', 'Power'),
        port('rst-2', 'RST 2', 'input', 'GPIO'),
        port('d0', 'D0 / RX', 'input', 'UART', 'D0'),
        port('d1', 'D1 / TX', 'output', 'UART', 'D1'),
      ],
    },
  },
  {
    libraryId: 'lib-raspberry-pi-4',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Raspberry Pi',
      model: '4 Model B',
      category: 'single-board-computer',
      location: '',
      ports: [
        port('p1-3v3', 'P1 / 3V3', 'input', 'Power'),
        port('p2-5v', 'P2 / 5V', 'input', 'Power'),
        port('p6-gnd', 'P6 / GND', 'input', 'Power'),
        port('p10-gpio15', 'P10 / GPIO15 RXD', 'input', 'UART'),
        port('usb-data', 'USB / Kinect data', 'input', 'USB'),
        port('p3-gpio2', 'P3 / GPIO2 SDA1', 'output', 'I2C'),
        port('p5-gpio3', 'P5 / GPIO3 SCL1', 'output', 'I2C'),
        port('p8-gpio14', 'P8 / GPIO14 TXD', 'output', 'UART'),
      ],
    },
  },
  {
    libraryId: 'lib-mpu6050-gy521',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'InvenSense / Generic',
      model: 'MPU6050 / GY-521',
      category: 'imu',
      location: '',
      notes: 'Dimensões e pinagem provisórias; confirme a variante física antes da montagem.',
      ...physicalDefinition(GY_521_MPU6050_FOOTPRINT),
      ports: [
        port('vcc', 'VCC', 'input', 'Power'),
        port('gnd', 'GND', 'input', 'Power'),
        port('scl', 'SCL', 'input', 'I2C'),
        port('sda', 'SDA', 'input', 'I2C'),
        port('xda', 'XDA', 'output', 'I2C'),
        port('xcl', 'XCL', 'output', 'I2C'),
        port('ad0', 'AD0', 'input', 'GPIO'),
        port('int', 'INT', 'output', 'GPIO'),
      ],
    },
  },
  {
    libraryId: 'lib-tb6612fng',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Toshiba / Generic',
      model: 'TB6612FNG',
      category: 'motor-driver',
      location: '',
      notes: 'Dimensões e pinagem provisórias; confirme a variante física antes da montagem.',
      ...physicalDefinition(TB6612FNG_FOOTPRINT),
      ports: [
        port('vm', 'VM', 'input', 'Power'),
        port('vcc', 'VCC', 'input', 'Power'),
        port('gnd', 'GND', 'input', 'Power'),
        port('ao1', 'AO1', 'output', 'Motor'),
        port('ao2', 'AO2', 'output', 'Motor'),
        port('bo2', 'BO2', 'output', 'Motor'),
        port('bo1', 'BO1', 'output', 'Motor'),
        port('gnd-2', 'GND 2', 'input', 'Power'),
        port('pwma', 'PWMA', 'input', 'PWM'),
        port('ain2', 'AIN2', 'input', 'GPIO'),
        port('ain1', 'AIN1', 'input', 'GPIO'),
        port('stby', 'STBY', 'input', 'GPIO'),
        port('bin1', 'BIN1', 'input', 'GPIO'),
        port('bin2', 'BIN2', 'input', 'GPIO'),
        port('pwmb', 'PWMB', 'input', 'PWM'),
        port('gnd-3', 'GND 3', 'input', 'Power'),
      ],
    },
  },
  {
    libraryId: 'lib-buzzer-active-12mm',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Buzzer ativo 12 mm',
      category: 'buzzer',
      location: '',
      notes: 'Componente polarizado; preserve os terminais + e - durante a montagem.',
      ...physicalDefinition(BUZZER_ACTIVE_12MM_FOOTPRINT),
      ports: [port('plus', '+', 'input', 'Lead'), port('minus', '-', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-resistor-1k',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Resistor axial 1 kOhm',
      category: 'resistor',
      location: '',
      notes: 'Vão ajustável entre 4 e 10 passos de pitch; corpo e bandas permanecem rígidos.',
      ...physicalDefinition(RESISTOR_1K_FOOTPRINT),
      ports: [port('a', '1', 'input', 'Lead'), port('b', '2', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-resistor-1k8',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Resistor axial 1,8 kOhm',
      category: 'resistor',
      location: '',
      notes: 'Vão ajustável entre 4 e 10 passos de pitch; corpo e bandas permanecem rígidos.',
      ...physicalDefinition(RESISTOR_1K8_FOOTPRINT),
      ports: [port('a', '1', 'input', 'Lead'), port('b', '2', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-capacitor-electrolytic-470uf',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Capacitor eletrolítico 470 uF / 25 V',
      category: 'capacitor',
      location: '',
      notes: 'Passo fixo de 2 pitches; componente polarizado.',
      ...physicalDefinition(CAP_470U_25V_FOOTPRINT),
      ports: [port('plus', '+', 'input', 'Lead'), port('minus', '-', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-capacitor-electrolytic-470uf-16v',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Capacitor eletrolítico 470 uF / 16 V',
      category: 'capacitor',
      location: '',
      notes: 'Passo fixo de 2 pitches; componente polarizado.',
      ...physicalDefinition(CAP_470U_16V_FOOTPRINT),
      ports: [port('plus', '+', 'input', 'Lead'), port('minus', '-', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-capacitor-ceramic-100nf',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'Capacitor cerâmico 100 nF',
      category: 'capacitor',
      location: '',
      notes: 'Passo fixo de 2 pitches; componente não polarizado.',
      ...physicalDefinition(CAP_100N_FOOTPRINT),
      ports: [port('a', '1', 'input', 'Lead'), port('b', '2', 'output', 'Lead')],
    },
  },
  {
    libraryId: 'lib-lm2596s',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Texas Instruments / Generic',
      model: 'LM2596S adjustable buck',
      category: 'voltage-regulator',
      location: '',
      ports: [
        port('in-plus', 'IN+', 'input', 'Power'),
        port('in-minus', 'IN-', 'input', 'Power'),
        port('out-plus', 'OUT+', 'output', 'Power'),
        port('out-minus', 'OUT-', 'output', 'Power'),
      ],
    },
  },
  {
    libraryId: 'lib-hall-a3144-lm393',
    template: {
      type: 'device',
      deviceId: '',
      manufacturer: 'Generic',
      model: 'A3144 / LM393 (4 vias — provisório)',
      category: 'hall-sensor',
      location: '',
      notes: 'Variante provisória de quatro vias; confirmar a serigrafia antes da montagem.',
      ports: [
        port('vcc', 'VCC', 'input', 'Power'),
        port('gnd', 'GND', 'input', 'Power'),
        port('ao', 'AO', 'output', 'GPIO'),
        port('do', 'DO', 'output', 'GPIO'),
      ],
    },
  },
];
