import { type YamlValue } from './wireviz-yaml';

/**
 * Domain types and validation for the WireViz *subset* this slice supports.
 *
 * Scope, deliberately narrow (see docs/wireviz-import-limits.md for the full
 * list): every `connections` entry must be exactly one cable wire between
 * exactly two connector pins — no multi-drop nets, no bundles, no junctions,
 * no autogenerated/omitted pin lists. A real-world WireViz document (e.g.
 * `felipedruzian/talus-droid`'s `hardware/wireviz/talus-power.yml`) uses
 * several of these constructs; this parser intentionally rejects them
 * instead of guessing. See docs/wireviz-import-limits.md for what's known
 * vs. unverified about the exact gap.
 */

export interface WireVizConnector {
  name: string;
  type?: string;
  pins: string[];
}

export interface WireVizCable {
  name: string;
  colors: string[];
}

export interface WireVizPinRef {
  connector: string;
  pin: string;
}

export interface WireVizConnection {
  source: WireVizPinRef;
  target: WireVizPinRef;
  cable: { name: string; wireIndex: number };
}

export interface WireVizDocument {
  connectors: WireVizConnector[];
  cables: WireVizCable[];
  connections: WireVizConnection[];
}

export class WireVizModelError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'WireVizModelError';
  }
}

export function parseWireVizDocument(raw: YamlValue): WireVizDocument {
  const root = expectObject(raw, 'document root');

  const connectors = parseConnectors(root['connectors']);
  const cables = parseCables(root['cables']);
  const connections = parseConnections(root['connections'], connectors, cables);

  return { connectors, cables, connections };
}

function parseConnectors(raw: YamlValue | undefined): WireVizConnector[] {
  const obj = expectObject(raw, 'connectors');
  return Object.entries(obj).map(([name, value]) => {
    const entry = expectObject(value, `connectors.${name}`);
    const pins = expectStringArray(entry['pins'], `connectors.${name}.pins`);
    if (pins.length === 0) {
      throw new WireVizModelError(`connectors.${name}.pins must not be empty`);
    }
    return { name, type: typeof entry['type'] === 'string' ? entry['type'] : undefined, pins };
  });
}

function parseCables(raw: YamlValue | undefined): WireVizCable[] {
  const obj = expectObject(raw, 'cables');
  return Object.entries(obj).map(([name, value]) => {
    const entry = expectObject(value, `cables.${name}`);
    const colors = expectStringArray(entry['colors'], `cables.${name}.colors`);
    return { name, colors };
  });
}

function parseConnections(
  raw: YamlValue | undefined,
  connectors: WireVizConnector[],
  cables: WireVizCable[],
): WireVizConnection[] {
  if (!Array.isArray(raw)) {
    throw new WireVizModelError('connections must be a list of connection sets');
  }
  const connectorsByName = new Map(connectors.map((c) => [c.name, c]));
  const cablesByName = new Map(cables.map((c) => [c.name, c]));

  return raw.map((entry, index) =>
    parseConnectionSet(entry, index, connectorsByName, cablesByName),
  );
}

function parseConnectionSet(
  raw: YamlValue,
  index: number,
  connectorsByName: ReadonlyMap<string, WireVizConnector>,
  cablesByName: ReadonlyMap<string, WireVizCable>,
): WireVizConnection {
  const label = `connections[${index}]`;
  if (!Array.isArray(raw) || raw.length !== 3) {
    throw new WireVizModelError(
      `${label}: this slice only supports a 2-endpoint connection (exactly 3 entries: connector, cable, connector) — got ${
        Array.isArray(raw) ? raw.length : typeof raw
      }`,
    );
  }

  const refs = raw.map((item, i) => parseSingleKeyRef(item, `${label}[${i}]`));
  const cableRefs = refs.filter((r) => cablesByName.has(r.key));
  const connectorRefs = refs.filter((r) => connectorsByName.has(r.key));

  if (cableRefs.length !== 1 || connectorRefs.length !== 2) {
    throw new WireVizModelError(
      `${label}: expected exactly one known cable and two known connectors, got cable=${cableRefs.length} connector=${connectorRefs.length}`,
    );
  }

  const [sourceRef, targetRef] = connectorRefs;
  const cableRef = cableRefs[0];
  const cable = getOrThrow(cablesByName, cableRef.key, label);

  if (cableRef.values.length !== 1) {
    throw new WireVizModelError(
      `${label}: this slice only supports a single wire index per cable reference (bundled/multi-wire refs are unsupported)`,
    );
  }
  const rawWireIndex = expectScalarString(
    cableRef.values[0],
    `${label}: cable "${cable.name}" wire index`,
  );
  const wireIndex = Number(rawWireIndex);
  if (!Number.isInteger(wireIndex) || wireIndex < 1 || wireIndex > cable.colors.length) {
    throw new WireVizModelError(
      `${label}: cable "${cable.name}" wire index ${rawWireIndex} is out of range (1..${cable.colors.length})`,
    );
  }

  return {
    source: parsePinRef(sourceRef, connectorsByName, label),
    target: parsePinRef(targetRef, connectorsByName, label),
    cable: { name: cable.name, wireIndex },
  };
}

function parsePinRef(
  ref: SingleKeyRef,
  connectorsByName: ReadonlyMap<string, WireVizConnector>,
  label: string,
): WireVizPinRef {
  if (ref.values.length !== 1) {
    throw new WireVizModelError(
      `${label}: this slice only supports a single pin per connector reference (multi-drop is unsupported)`,
    );
  }
  const pin = expectScalarString(ref.values[0], `${label}: connector "${ref.key}" pin`);
  const connector = getOrThrow(connectorsByName, ref.key, label);
  if (!connector.pins.includes(pin)) {
    throw new WireVizModelError(
      `${label}: connector "${ref.key}" has no pin "${pin}" (declared pins: ${connector.pins.join(', ')})`,
    );
  }
  return { connector: ref.key, pin };
}

interface SingleKeyRef {
  key: string;
  values: YamlValue[];
}

function parseSingleKeyRef(raw: YamlValue, label: string): SingleKeyRef {
  const obj = expectObject(raw, label);
  const keys = Object.keys(obj);
  if (keys.length !== 1) {
    throw new WireVizModelError(`${label}: expected a single-key mapping, got ${keys.length} keys`);
  }
  const key = keys[0];
  const value = obj[key];
  if (!Array.isArray(value)) {
    throw new WireVizModelError(`${label}.${key}: expected a list of pin/wire references`);
  }
  return { key, values: value };
}

function getOrThrow<V>(map: ReadonlyMap<string, V>, key: string, label: string): V {
  const value = map.get(key);
  if (value === undefined) {
    throw new WireVizModelError(`${label}: no entry for "${key}"`);
  }
  return value;
}

function expectObject(raw: YamlValue | undefined, label: string): Record<string, YamlValue> {
  if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
    throw new WireVizModelError(`${label}: expected a mapping`);
  }
  return raw;
}

function expectStringArray(raw: YamlValue | undefined, label: string): string[] {
  if (!Array.isArray(raw)) {
    throw new WireVizModelError(`${label}: expected a list`);
  }
  return raw.map((value, index) => expectScalarString(value, `${label}[${index}]`));
}

function expectScalarString(raw: YamlValue | undefined, label: string): string {
  if (typeof raw !== 'string' && typeof raw !== 'number') {
    throw new WireVizModelError(`${label}: expected a string or number`);
  }
  return String(raw);
}
